access:
  - agent: value-management-officier.agent.md
    artifact: portfolio-manifest.artifact.schema.json
  - agent: value-management-officier.agent.md
    artifact: product-manifest.artifact.schema.json

  - agent: release-train-engineer.agent.md
    artifact: art-manifest.artifact.schema.json
  - agent: release-train-engineer.agent.md
    artifact: pain-point.artifact.schema.json

  - agent: scrum-master.agent.md
    artifact: team-manifest.artifact.schema.json
  - agent: scrum-master.agent.md
    artifact: plan.artifact.schema.json
  - agent: scrum-master.agent.md
    artifact: progress.artifact.schema.json

  - agent: business-owner.agent.md
    artifact: strategic-themes.artifact.schema.json
  - agent: business-owner.agent.md
    artifact: portfolio-vision.artifact.schema.json
  - agent: business-owner.agent.md
    artifact: portfolio-roadmap.artifact.schema.json
  - agent: business-owner.agent.md
    artifact: epic.artifact.schema.json
  - agent: business-owner.agent.md
    artifact: lean-business-case.artifact.schema.json

  - agent: enterprise-architect.agent.md
    artifact: architecture-vision.artifact.schema.json
  - agent: enterprise-architect.agent.md
    artifact: epic-enabler.artifact.schema.json

  - agent: product-manager.agent.md
    artifact: objectives.artifact.schema.json
  - agent: product-manager.agent.md
    artifact: risks.artifact.schema.json
  - agent: product-manager.agent.md
    artifact: product-vision.artifact.schema.json
  - agent: product-manager.agent.md
    artifact: product-roadmap.artifact.schema.json
  - agent: product-manager.agent.md
    artifact: feature.artifact.schema.json

  - agent: system-architect.agent.md
    artifact: adr.artifact.schema.json
  - agent: system-architect.agent.md
    artifact: architecture-review.artifact.schema.json
  - agent: system-architect.agent.md
    artifact: architecture-runway.artifact.schema.json
  - agent: system-architect.agent.md
    artifact: nfr-list.artifact.schema.json
  - agent: system-architect.agent.md
    artifact: feature-enabler.artifact.schema.json

  - agent: product-owner.agent.md
    artifact: story.artifact.schema.json

  - agent: developer.agent.md
    artifact: story-enabler.artifact.schema.json
  - agent: developer.agent.md
    artifact: feasibility-review.artifact.schema.json

  - agent: operator.agent.md
    artifact: operability-review.artifact.schema.json

  - agent: quality-engineer.agent.md
    artifact: qa-signoff.artifact.schema.json

  - agent: security-expert.agent.md
    artifact: security-review.artifact.schema.json

  - agent: ux-designer.agent.md
    artifact: ux-review.artifact.schema.json
